[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
version = "0.0.1"
name = "petstream"
dependencies = [
    "absl-py",
    "disaggregation",
    "flatbuffers",
    "jax>=0.4.24",
    "jaxlib>=0.4.24",
    "pytest",
    "sentencepiece",
    "tensorflow",
    "torch",
    # torch_xla2
]

requires-python = ">=3.10"
license = {file = "LICENSE"}
